[primary]
kanengo-primary ansible_host=192.168.106.132

[standby]
mpemba-standby ansible_host=192.168.106.131

[msg_db_servers:children]
primary
standby

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
